project:
  name: "spring-demo"
  version: "1.1.0"

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xietaojie.lab.springdemo.common.dal
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: statement
    jdbc-type-for-null: null
